### ISSUE TITLE
Meta requires a 'static String?

### ISSUE THREAD

**Issue by ProjectMoon** [gemrest/germ#2]
I'm making good use of your library in a small project. But I can't parse the meta from a Gemini response into a structured representation, because the `from_string` function requires a `'static` lifetime. This seems like an oversight maybe?

```rust
let resp = germ::request::request(url)?;
let meta = germ::meta::Meta::from_string(resp.meta());
```
This is not possible, because `resp.meta()` does not have a `'static` lifetime. Is there a way to parse the response Meta into the struct?

**Comment by Fuwn** [comment]
Thank you for bringing this to my attention. The latest release, `0.3.11`, includes a fix.

**Comment by ProjectMoon** [comment]
Great. I've already integrated both bug fixes into my own project!
